import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The house icon library: Lamina-style doodle icons generated by an image model
 * (scripts/generate-icon-library.ts / worker/iconLibraryGen.ts), vectorized and
 * stored under assets/generated/icon-library/. This is the PRIMARY icon source —
 * OpenMoji is the fallback when a concept has no library icon yet.
 *
 * Every entry is one concept: a vector SVG (color paths + a <g id="line"> outline
 * group, so the renderer's outline-then-fill reveal works unchanged) plus the
 * source PNG kept for reference/regeneration.
 */

export type IconLibraryEntry = {
  id: string; // slug, unique
  concept: string; // the concept the icon depicts ("rocket", "credit score")
  label: string; // human label shown in tooling
  synonyms: string[]; // extra lookup terms
  svgPath: string; // repo-relative vector path
  pngPath?: string; // repo-relative source raster
  model?: string; // image model that drew it
  createdAt: string;
  qa?: { depicts: boolean; styleOk: boolean; inkFrac: number; coverage: number };
};

type IconLibraryManifest = {
  provider: "icon-library";
  generatedAt: string;
  total: number;
  entries: IconLibraryEntry[];
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
export const iconLibraryRoot = path.join(root, "assets", "generated", "icon-library");
export const iconLibrarySvgDir = path.join(iconLibraryRoot, "svg");
export const iconLibraryPngDir = path.join(iconLibraryRoot, "png");
const manifestPath = path.join(iconLibraryRoot, "manifest.json");

// Saturated flat fills (Lamina-style) that every library icon is snapped to,
// plus the near-black outline. Exported so the generator and any tooling agree.
export const ICON_OUTLINE = "#1a1a1a";
export const ICON_PALETTE = [
  "#4da3ff", // blue
  "#ffd43b", // yellow
  "#ff6b6b", // red
  "#51cf66", // green
  "#ffa94d", // orange
  "#9775fa", // purple
  "#66d9e8", // cyan
  "#f783ac", // pink
];

let manifestCache: IconLibraryManifest | undefined;
let lookupCache: Map<string, IconLibraryEntry> | undefined;

export function normalizeConcept(value: string): string {
  return value
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, " ")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

export function conceptSlug(value: string): string {
  return normalizeConcept(value).replace(/\s+/g, "-") || "concept";
}

function emptyManifest(): IconLibraryManifest {
  return { provider: "icon-library", generatedAt: new Date().toISOString(), total: 0, entries: [] };
}

function loadManifest(): IconLibraryManifest {
  if (manifestCache) return manifestCache;
  manifestCache = existsSync(manifestPath)
    ? (JSON.parse(readFileSync(manifestPath, "utf8")) as IconLibraryManifest)
    : emptyManifest();
  return manifestCache;
}

function buildLookup(): Map<string, IconLibraryEntry> {
  if (lookupCache) return lookupCache;
  lookupCache = new Map();
  for (const entry of loadManifest().entries) {
    // This map is an identity lookup, not search. Broad synonyms such as
    // "water" on an anchor are useful retrieval tags, but must never turn a
    // semantic key like `waterDrop` into an exact anchor match.
    for (const term of [entry.id, entry.concept, entry.label]) {
      const norm = normalizeConcept(term);
      if (norm && !lookupCache.has(norm)) lookupCache.set(norm, entry);
    }
  }
  return lookupCache;
}

/** Drop in-memory caches so the next lookup re-reads the manifest (after a write). */
export function reloadIconLibrary(): void {
  manifestCache = undefined;
  lookupCache = undefined;
}

export function iconLibraryEntries(): IconLibraryEntry[] {
  return loadManifest().entries;
}

export function iconLibraryEntryById(id: string): IconLibraryEntry | null {
  return loadManifest().entries.find((entry) => entry.id === id) ?? null;
}

/**
 * Direct (exact, normalized) concept/synonym lookup — the highest-priority icon
 * resolution tier. Sync + cheap so the render-time resolver can call it.
 */
export function findLibraryIcon(key: string, label?: string): IconLibraryEntry | null {
  const lookup = buildLookup();
  for (const term of [key, label]) {
    if (!term) continue;
    const entry = lookup.get(normalizeConcept(term));
    if (entry && existsSync(path.join(root, entry.svgPath))) return entry;
  }
  return null;
}

/** Persist (or replace) a library entry and its manifest row. */
export function writeLibraryEntry(entry: IconLibraryEntry): IconLibraryEntry {
  const manifest = loadManifest();
  const entries = [...manifest.entries.filter((item) => item.id !== entry.id), entry].sort((a, b) =>
    a.id.localeCompare(b.id),
  );
  const next: IconLibraryManifest = {
    provider: "icon-library",
    generatedAt: new Date().toISOString(),
    total: entries.length,
    entries,
  };
  mkdirSync(iconLibraryRoot, { recursive: true });
  writeFileSync(manifestPath, `${JSON.stringify(next, null, 2)}\n`, "utf8");
  manifestCache = next;
  lookupCache = undefined;
  return entry;
}

export function removeLibraryEntry(id: string): boolean {
  const manifest = loadManifest();
  const entries = manifest.entries.filter((item) => item.id !== id);
  if (entries.length === manifest.entries.length) return false;
  const next: IconLibraryManifest = {
    provider: "icon-library",
    generatedAt: new Date().toISOString(),
    total: entries.length,
    entries,
  };
  mkdirSync(iconLibraryRoot, { recursive: true });
  writeFileSync(manifestPath, `${JSON.stringify(next, null, 2)}\n`, "utf8");
  manifestCache = next;
  lookupCache = undefined;
  return true;
}
